// Rival park owners. Each has a strategic bias + a mouth.
export const PERSONALITIES = {
  baron: {
    id: 'baron',
    name: 'Baron Von Loop',
    title: 'The Engineer',
    parkName: 'Loopenstein Heights',
    avatar: '🎩',
    color: '#8e44ad',
    blurb: 'Coaster-obsessed turtle. Builds a fortress of rides, then crushes you with heavy hitters.',
    econ: 0.45, army: 0.3, defense: 0.25,
    coasterLove: 1.6, aggression: 0.8, patience: 1.3,
    favorites: { strongman: 1.3, cannoneer: 1.25, mascot: 1.1, giant: 1.2 },
    taunts: {
      start: ['Welcome to my domain. Mind the track.', 'Physics is on MY side.', 'I have calculated your defeat to three decimal places.'],
      coaster: ['Behold! {name}! Excitement {E}!', 'My new coaster flattens trespassers AND prints money.', 'Loops, drops, and your army under the wheels.'],
      winRound: ['As the blueprints predicted.', 'Your little soldiers did not pass inspection.', 'Another successful test run.'],
      loseRound: ['An engineering setback. Temporary.', 'Hmph. Recalibrating.', 'That was merely a stress test.'],
      counter: ['{unit}? I have an equation for that.', 'I see your {unit}. I have prepared {counter}.'],
      castleHit: ['My beautiful castle!', 'Do you know how much that masonry cost?!'],
      hitYou: ['Your castle has structural issues.', 'Load-bearing wall? Not anymore.'],
      hold: ['Come to me. My defenses are hungry.', 'I shall wait behind my splendid machinery.'],
      charge: ['Engage the heavy machinery!', 'Forward, my beautiful brutes!'],
      win: ['QED. Your park is condemned.', 'Loopenstein stands supreme!'],
      lose: ['Impossible! My calculations...', 'Fine. Keep your wobbly little park.'],
    },
  },
  mayhem: {
    id: 'mayhem',
    name: 'Madame Mayhem',
    title: 'The Warlord',
    parkName: 'Mayhem Mountain',
    avatar: '🔥',
    color: '#e74c3c',
    blurb: 'All gas, no brakes. Rushes early with swarms and clowns. Economy? What economy?',
    econ: 0.22, army: 0.72, defense: 0.06,
    coasterLove: 0.35, aggression: 1.5, patience: 0.6,
    favorites: { janitor: 1.35, clown: 1.35, bumper: 1.25, cannonball: 1.2 },
    taunts: {
      start: ['Hope you like visitors. LOTS of visitors.', 'Rides are for cowards. CHARGE!', 'I skipped the tutorial. And the brakes.'],
      coaster: ['Fine, ONE coaster. For morale.', 'Wheee! Now back to war.'],
      winRound: ['HA! Again! AGAIN!', 'Your guests are running. Smart guests.', 'Mop-wielding perfection.'],
      loseRound: ['I have more janitors. INFINITE janitors.', 'That tickled.', 'Pfft. Warm-up round.'],
      counter: ['Oh, {unit}? Cute. Here come my {counter}.', 'More {unit}? More {counter}!'],
      castleHit: ['HEY! That was my favorite turret!', 'You broke it! YOU BOUGHT IT!'],
      hitYou: ['Knock knock! It is me! With a mallet!', 'Your castle looks better in pieces.'],
      hold: ['...Fine. We wait. For ONE round.', 'Regrouping! Not retreating! Regrouping!'],
      charge: ['CHAAAAARGE!', 'EVERYBODY GO! GO GO GO!'],
      win: ['MAYHEM WINS! FIREWORKS! MORE FIREWORKS!', 'Your park is now MY parking lot.'],
      lose: ['This is not over! ...It is over, isn\'t it.', 'I demand a rematch! And a bigger mop!'],
    },
  },
  penny: {
    id: 'penny',
    name: 'Penny Pincher',
    title: 'The Tycoon',
    parkName: 'Profitopia',
    avatar: '💰',
    color: '#f1c40f',
    blurb: 'Greedy economist. Builds a money machine, then buys giants by the dozen.',
    econ: 0.62, army: 0.28, defense: 0.1,
    coasterLove: 1.2, aggression: 0.7, patience: 1.6,
    favorites: { giant: 1.5, popper: 1.2, mascot: 1.1, ringmaster: 1.15 },
    taunts: {
      start: ['Every guest is a customer. Every customer is ammunition.', 'Let\'s talk numbers. Mostly MY numbers.', 'Time is money. You are wasting both.'],
      coaster: ['{name}: {E} excitement, ${price} a ride. Kerching!', 'Another coaster. Another revenue stream.'],
      winRound: ['A sound investment.', 'Your losses are my quarterly gains.', 'Excellent returns this round.'],
      loseRound: ['A minor dip in the market.', 'I can afford to lose. Can you?', 'Write it off as a tax deduction.'],
      counter: ['{unit}? Market research says: {counter}.', 'I bought {counter} in bulk. For your {unit}.'],
      castleHit: ['Do you know what that castle is WORTH?!', 'I am sending you the invoice.'],
      hitYou: ['Your property value is plummeting.', 'I\'ll buy your ruins at a discount.'],
      hold: ['Why fight when I can compound interest?', 'Patience. The giants are on backorder.'],
      charge: ['Deploy the capital!', 'It is time to liquidate your assets. Violently.'],
      win: ['Hostile takeover complete!', 'Profitopia acquires your park. Sign here.'],
      lose: ['I\'ll... just buy another park.', 'Bankrupt?! ME?!'],
    },
  },
  gustavo: {
    id: 'gustavo',
    name: 'The Great Gustavo',
    title: 'The Showman',
    parkName: 'Gustavo\'s Grand Spectacle',
    avatar: '🎪',
    color: '#16a085',
    blurb: 'A master showman who reads your army like a script and writes the perfect counter.',
    econ: 0.42, army: 0.44, defense: 0.14,
    coasterLove: 1.0, aggression: 1.0, patience: 1.0,
    favorites: { ringmaster: 1.3, cannonball: 1.2, clown: 1.1, cannoneer: 1.05 },
    counterFocus: 1.35,
    taunts: {
      start: ['Ladies and gentlemen... the show begins!', 'Welcome to the greatest show on dirt!', 'Every battle needs a villain. Hello!'],
      coaster: ['Presenting... {name}! Excitement {E}!', 'The crowd demands spectacle. I deliver.'],
      winRound: ['The audience roars!', 'A standing ovation for my troupe!', 'And scene!'],
      loseRound: ['A dramatic twist! The hero stumbles!', 'Every show needs tension.', 'Intermission. Then revenge.'],
      counter: ['Your {unit} act is predictable. Enter: {counter}!', 'I have seen this show. The {counter} win.'],
      castleHit: ['Heckler in the castle!', 'Stop damaging my set!'],
      hitYou: ['Bring down the curtain... and the castle!', 'Encore! ENCORE!'],
      hold: ['Let them come to the stage.', 'We wait for our cue.'],
      charge: ['Showtime!', 'On with the show!'],
      win: ['What a finale! Thank you, thank you!', 'The Great Gustavo takes a bow!'],
      lose: ['The critics will hate this.', 'Bravo... bravo. You stole the show.'],
    },
  },
};

export const DIFFICULTIES = {
  easy: { id: 'easy', name: 'Easy', noise: 0.55, delay: 2.4, income: 0.82, counter: 0.35, formation: 0.4, coasterTries: 10, repair: 0.4, micro: 0.6, peek: false },
  normal: { id: 'normal', name: 'Normal', noise: 0.25, delay: 1.2, income: 1.0, counter: 0.8, formation: 0.85, coasterTries: 30, repair: 0.8, micro: 0.9, peek: false },
  hard: { id: 'hard', name: 'Hard', noise: 0.1, delay: 0.6, income: 1.12, counter: 1.0, formation: 1, coasterTries: 60, repair: 1, micro: 1, peek: false },
  brutal: { id: 'brutal', name: 'Brutal', noise: 0.04, delay: 0.35, income: 1.35, counter: 1.1, formation: 1, coasterTries: 90, repair: 1, micro: 1, peek: true },
};
